# Generated by Django 5.2.4 on 2025-07-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='collage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage_app.collage'),
        ),
    ]
